### ISSUE TITLE
[INVALID] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [fernandotcl/btag#1]
Dear Fernando,
Could you be so kind to generate ```.exe``` for the rest of us who use Windows, if possible?

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by fernandotcl** [comment]
Nope, not something I can provide, sorry.

**Comment by sergeevabc** [comment]
Because it is not possible by design or you lack some of the required tools to generate *.exe?

**Comment by fernandotcl** [comment]
I don't know how btag would even work on Windows, and I lack tools and interest, sorry.
